# Data Retrievial, Cleaning and Manipulation Using Python Pandas

*by Bernardo Di Chiara*

**October 02 2018**

In this project, three files are loaded in Python as Panda dataframes. Those dataframes are cleansed and then merged into a single data set.

The dataset is further manipulated to find average values, max values, etc ... New columns are added to calculate new variables. Then data from a Python dictionary is added to do further data manipulation and new dataframes are created.

The work has been done by using Juniper Notebook.

## 1.

The excell file `Energy Indicators.xls`, which is a list of indicators of energy supply and renewable electricity production from the United Nations is loaded.

The data set is cleansed, for example, by excluding footer and header information. Some columns are renamed. Null values are clearly marked. Some unit conversion is also done to facilitate further calculations. Some further modification to the dataframe values is done to facilitate the merging of the dataframes.

Next, the csv the file `world_bank.csv`, which is a file containing countries' GDP from 1960 to 2015 from Word Bank, is loaded. Some modification is done also to this file to remove the header and modify certain values to allow merging with the other dataframes.

Finally, the file `scimagojr-3.xlsx` is loaded. This file  ranks countries based on their journal contributions in the Energy Engineering and Power Technology areas.

The three datasets are joined by using the country names as keys.

The merged dataframe is filtered to leave only the last 10 years (2006-2015) of GDP data and only the top 15 ranked countries by the Sciamgo Journal.

In [161]:
def issue_one():
    import pandas as pd
    import numpy as np
    ### Handling the Energy file
    ## Storing the data from the excel file into a Panda dataframe
    excel_file = 'Energy Indicators.xls'
    energy = pd.read_excel(excel_file, skiprows=16) # skipping the first rows that are not part of the table
    ## Cleaning out not needed rows and columns
    energy = energy.drop(0) # dropping the row containing the units
    energy = energy.drop(energy.columns[[0, 1]], axis=1) # dropping the unnecessary columns
    energy = energy.drop(energy.index[227:265])# dropping the footer of the original excel file
    ## Renaming the columns
    energy = energy.rename(columns={
        'Unnamed: 2':'Country',
        'Energy Supply per capita':'Energy Supply per Capita',
        'Renewable Electricity Production':'% Renewable'})
    ## Modifying cell contents
    # Marking clearly NA values
    energy = energy.replace('...',np.NaN)
    # Converting Energy Supply from petajoules into gigajoules
    energy['Energy Supply'] = energy['Energy Supply']*1000000
    # Renaming Countries
    energy['Country'] = energy['Country'].replace({
        'Australia1': 'Australia',
        'China2': 'China',
        'China, Hong Kong Special Administrative Region3': 'Hong Kong',
        'China, Macao Special Administrative Region4': 'Macao',
        'Denmark5': 'Denmark',
        'France6': 'France',
        'Greenland7': 'Greenland',
        'Indonesia8': 'Indonesia',
        'Italy9': 'Italy',
        'Japan10': 'Japan',
        'Kuwait11': 'Kuwait',
        'Netherlands12': 'Netherlands',
        'Portugal13': 'Portugal',
        'Saudi Arabia14': 'Saudi Arabia',
        'Serbia15': 'Serbia',
        'Spain16': 'Spain',
        'Switzerland17': 'Switzerland',
        'Ukraine18': 'Ukraine',
        'United Kingdom of Great Britain and Northern Ireland19': 'United Kingdom', 
        'United States of America20': 'United States',
        'Republic of Korea': 'South Korea'
    })
    energy['Country'] = energy['Country'].str.replace(r" \(.*\)","") # removing all what is contained in parenthesis, 
    # including the space before
    ### Handling the GDP file
    ## Storing the data from the csv file into a Panda dataframe
    GDP = pd.read_csv("world_bank.csv", skiprows=4)
    ## Modifying cell contents
     # Renaming Countries
    GDP['Country Name'] = GDP['Country Name'].replace({
        'Korea, Rep.': 'South Korea',
        'Iran, Islamic Rep.': 'Iran',
        'Hong Kong SAR, China': 'Hong Kong'                 })
    ### Handling the ScimEn file
    ## Storing the data from the excel file into a Panda dataframe
    ScimEn = pd.read_excel('scimagojr-3.xlsx')
    ### Merging the three data sets
    # Merging energy and GDP
    merged_e_G = pd.merge(energy, GDP, how='inner', left_on='Country', right_on='Country Name')
    # Selecting the necessary columns
    merged_e_G = merged_e_G[merged_e_G.columns[[0, 1, 2, 3, -10, -9, -8, -7, -6, -5, -4, -3, -2, -1]]]
    # Merging with ScimEn
    merged = pd.merge(ScimEn, merged_e_G, how='inner', left_on='Country', right_on='Country')
    # Selecting the wished rows (first 15 entries)
    merged = merged[merged['Rank'] <= 15]
    # Changing the index into the Country
    merged = merged.set_index('Country')
    return merged
issue_one()

,Rank,Documents,Citable documents,Citations,Self-citations,Citations per document,H index,Energy Supply,Energy Supply per Capita,% Renewable,2006,2007,2008,2009,2010,2011,2012,2013,2014,2015
Country,,,,,,,,,,,,,,,,,,,,
China,1,127050,126767,597237,411683,4.70,138,1.271910e+11,93.0,19.754910,3.992331e+12,4.559041e+12,4.997775e+12,5.459247e+12,6.039659e+12,6.612490e+12,7.124978e+12,7.672448e+12,8.230121e+12,8.797999e+12
United States,2,96661,94747,792274,265436,8.20,230,9.083800e+10,286.0,11.570980,1.479230e+13,1.505540e+13,1.501149e+13,1.459484e+13,1.496437e+13,1.520402e+13,1.554216e+13,1.577367e+13,1.615662e+13,1.654857e+13
Japan,3,30504,30287,223024,61554,7.31,134,1.898400e+10,149.0,10.232820,5.496542e+12,5.617036e+12,5.558527e+12,5.251308e+12,5.498718e+12,5.473738e+12,5.569102e+12,5.644659e+12,5.642884e+12,5.669563e+12
United Kingdom,4,20944,20357,206091,37874,9.84,139,7.920000e+09,124.0,10.600470,2.419631e+12,2.482203e+12,2.470614e+12,2.367048e+12,2.403504e+12,2.450911e+12,2.479809e+12,2.533370e+12,2.605643e+12,2.666333e+12
Russian Federation,5,18534,18301,34266,12422,1.85,57,3.070900e+10,214.0,17.288680,1.385793e+12,1.504071e+12,1.583004e+12,1.459199e+12,1.524917e+12,1.589943e+12,1.645876e+12,1.666934e+12,1.678709e+12,1.616149e+12
Canada,6,17899,17620,215003,40930,12.01,149,1.043100e+10,296.0,61.945430,1.564469e+12,1.596740e+12,1.612713e+12,1.565145e+12,1.613406e+12,1.664087e+12,1.693133e+12,1.730688e+12,1.773486e+12,1.792609e+12
Germany,7,17027,16831,140566,27426,8.26,126,1.326100e+10,165.0,17.901530,3.332891e+12,3.441561e+12,3.478809e+12,3.283340e+12,3.417298e+12,3.542371e+12,3.556724e+12,3.567317e+12,3.624386e+12,3.685556e+12
India,8,15005,14841,128763,37209,8.58,115,3.319500e+10,26.0,14.969080,1.265894e+12,1.374865e+12,1.428361e+12,1.549483e+12,1.708459e+12,1.821872e+12,1.924235e+12,2.051982e+12,2.200617e+12,2.367206e+12
France,9,13153,12973,130632,28601,9.93,114,1.059700e+10,166.0,17.020280,2.607840e+12,2.669424e+12,2.674637e+12,2.595967e+12,2.646995e+12,2.702032e+12,2.706968e+12,2.722567e+12,2.729632e+12,2.761185e+12
South Korea,10,11983,11923,114675,22595,9.57,104,1.100700e+10,221.0,2.279353,9.410199e+11,9.924316e+11,1.020510e+12,1.027730e+12,1.094499e+12,1.134796e+12,1.160809e+12,1.194429e+12,1.234340e+12,1.266580e+12
Italy,11,10964,10794,111850,26661,10.20,106,6.530000e+09,109.0,33.667230,2.202170e+12,2.234627e+12,2.211154e+12,2.089938e+12,2.125185e+12,2.137439e+12,2.077184e+12,2.040871e+12,2.033868e+12,2.049316e+12
Spain,12,9428,9330,123336,23964,13.08,115,4.923000e+09,106.0,37.968590,1.414823e+12,1.468146e+12,1.484530e+12,1.431475e+12,1.431673e+12,1.417355e+12,1.380216e+12,1.357139e+12,1.375605e+12,1.419821e+12
Iran,13,8896,8819,57470,19125,6.46,72,9.172000e+09,119.0,5.707721,3.895523e+11,4.250646e+11,4.289909e+11,4.389208e+11,4.677902e+11,4.853309e+11,4.532569e+11,4.445926e+11,4.639027e+11,NaN
Australia,14,8831,8725,90765,15606,10.28,107,5.386000e+09,231.0,11.810810,1.021939e+12,1.060340e+12,1.099644e+12,1.119654e+12,1.142251e+12,1.169431e+12,1.211913e+12,1.241484e+12,1.272520e+12,1.301251e+12
Brazil,15,8668,8596,60702,14396,7.00,86,1.214900e+10,59.0,69.648030,1.845080e+12,1.957118e+12,2.056809e+12,2.054215e+12,2.208872e+12,2.295245e+12,2.339209e+12,2.409740e+12,2.412231e+12,2.319423e+12

## 2.

Let's check what is the average GDP over the last 10 years for each country.

In [162]:
def issue_two():
    import pandas as pd
    Top15 = issue_one() # merged and filtered dataframe
    # Calculating the average GDP over the last 10 years for each country
    avgGDP = Top15[['2006', '2007', '2008', '2009', '2010', '2011', '2012', '2013', '2014', '2015']].mean(axis=1)
    return avgGDP.sort_values(ascending=False) # Sorting the results in descending order
issue_two()

Country
United States         1.536434e+13
China                 6.348609e+12
Japan                 5.542208e+12
Germany               3.493025e+12
France                2.681725e+12
United Kingdom        2.487907e+12
Brazil                2.189794e+12
Italy                 2.120175e+12
India                 1.769297e+12
Canada                1.660647e+12
Russian Federation    1.565459e+12
Spain                 1.418078e+12
Australia             1.164043e+12
South Korea           1.106715e+12
Iran                  4.441558e+11
dtype: float64

## 3.

The following code will show by how much had the GDP changed over the 10 year span for the country with the 6th largest average GDP.

In [163]:
# From 2. we can see that the country with the 6th largest average GDP is United Kingdom

In [164]:
def issue_three():
    import pandas as pd
    Top15 = issue_one() # merged and filtered dataframe
    # Calculating the GDP change over the last 10 years for each country
    Top15['diffGDP'] = Top15['2015'] - Top15['2006']
    # Extracting the value for United Kingdom
    diffGDP_UK = Top15.loc['United Kingdom', 'diffGDP']
    return diffGDP_UK
issue_three()

246702696075.3999

## 4.

Let's calculate what is the mean Energy Supply per Capita.

In [165]:
def issue_four():
    import pandas as pd
    Top15 = issue_one()
    return Top15['Energy Supply per Capita'].mean()
issue_four()

157.6

## 5.

It would be interesting to know what country has the maximum % Renewable and what is the percentage.

In [166]:
def issue_five():
    import pandas as pd
    Top15 = issue_one() # merged and filtered dataframe
    # Finding the country with the maximum % Renewable and storing the related data in a new dataframe
    mRenew = Top15[Top15['% Renewable'] == Top15['% Renewable'].max()]
    # Putting the result in a tuple
    mRenewResult = (mRenew.index[0],Top15['% Renewable'].max()) # name of the country, % Renewable value
    return mRenewResult
issue_five()

('Brazil', 69.648030000000006)

## 6.

Let's create a new column that is the ratio of Self Citations to Total Citations and find out what is the maximum value for this new column and what country has the highest ratio.

In [167]:
def issue_six():
    import pandas as pd
    Top15 = issue_one() # merged and filtered dataframe
    # Creating a new column with the ratio of Self-Citations to Total Citations
    Top15['Self_Total_Cit_Ratio'] = Top15['Self-citations'] / Top15['Citations']
    # Finding the country which has the maximum value and putting the related data in a new dataframe
    mCitRation = Top15[Top15['Self_Total_Cit_Ratio'] == Top15['Self_Total_Cit_Ratio'].max()]
    # Putting the result in a tuple
    mCitRationResult = (mCitRation.index[0],Top15['Self_Total_Cit_Ratio'].max()) # name of the country, citation ratio
    return mCitRationResult
issue_six()

('China', 0.68931261793894216)

## 7.

Now let's create a column that estimates the population using Energy Supply and Energy Supply per capita and find out what  is the third most populous country according to this estimate.

In [168]:
def issue_seven():
    import pandas as pd
    Top15 = issue_one() # merged and filtered dataframe
    # Creating a new column with the estimated polulation
    Top15['Population'] = Top15['Energy Supply'] / Top15['Energy Supply per Capita']
    # Sorting the resulting series according to decreasing population
    mPop = Top15['Population'].sort_values(ascending=False)
    # Extracting the country name corresponding to the third place
    return mPop.index[2]
issue_seven()

'United States'

## 8.

Let's create a column that estimates the number of citable documents per person and find out what is the correlation between the number of citable documents per capita and the energy supply per capita.

In [169]:
def issue_eight():
    import pandas as pd
    Top15 = issue_one() # merged and filtered dataframe
    # Creating a new column with the estimated polulation (as done in 7.)
    Top15['Population'] = Top15['Energy Supply'] / Top15['Energy Supply per Capita']
    # Creating a new column with the number of citable documents per person
    Top15['CitDoc Per Capita'] = Top15['Citable documents'] / Top15['Population']
    # Finding the correlation between the number of citable documents per capita and the energy supply per capita    
    return Top15['CitDoc Per Capita'].corr(Top15['Energy Supply per Capita'])
issue_eight()

0.79400104354429424

## 9.

Let's add a new column which contains 1 if the country's % Renewable value is at or above the median for all countries in the top 15 list, and a 0 if the country's % Renewable value is below the median.

In [170]:
def issue_nine():
    import pandas as pd
    Top15 = issue_one() # merged and filtered dataframe
    # Creating a new column identifying the countrues with % Renewable value at or above the median
    HighRenew = Top15['% Renewable'] >= Top15['% Renewable'].median()
    return HighRenew.astype(int) # Converting the Series from boolean to integer type
issue_nine()

Country
China                 1
United States         0
Japan                 0
United Kingdom        0
Russian Federation    1
Canada                1
Germany               1
India                 0
France                1
South Korea           0
Italy                 1
Spain                 1
Iran                  0
Australia             0
Brazil                1
Name: % Renewable, dtype: int64

## 10.

The following dictionary is used to group the Countries by Continent. Then a new dataframe is created to display the sample size (the number of countries in each continent), and the sum, mean, and standard deviation for the estimated population of each country.

```python
ContinentDict  = {'China':'Asia', 
                  'United States':'North America', 
                  'Japan':'Asia', 
                  'United Kingdom':'Europe', 
                  'Russian Federation':'Europe', 
                  'Canada':'North America', 
                  'Germany':'Europe', 
                  'India':'Asia',
                  'France':'Europe', 
                  'South Korea':'Asia', 
                  'Italy':'Europe', 
                  'Spain':'Europe', 
                  'Iran':'Asia',
                  'Australia':'Australia', 
                  'Brazil':'South America'}
```

In [171]:
def issue_ten():
    import pandas as pd
    import numpy as np
    Top15 = issue_one() # merged and filtered dataframe
    # Mapping Countries to Continents
    ContinentDict  = {'China':'Asia', 
                  'United States':'North America', 
                  'Japan':'Asia', 
                  'United Kingdom':'Europe', 
                  'Russian Federation':'Europe', 
                  'Canada':'North America', 
                  'Germany':'Europe', 
                  'India':'Asia',
                  'France':'Europe', 
                  'South Korea':'Asia', 
                  'Italy':'Europe', 
                  'Spain':'Europe', 
                  'Iran':'Asia',
                  'Australia':'Australia', 
                  'Brazil':'South America'}
    # Adding a new column containing the Continents
    Top15['Continent'] = ContinentDict.values()
    # Creating a new column with the estimated polulation
    Top15['Population'] = (Top15['Energy Supply'] / Top15['Energy Supply per Capita'])
    # Grouping by continent and retrieving the number of Countries (size of the group), sum, mean and standard deviation for the population
    Continents = Top15.set_index('Continent').groupby(level=0)['Population'].agg({'size': np.size, 'sum': np.sum, 'mean': np.mean, 'std': np.std})
    return Continents
issue_ten()

               size           sum          mean           std
Continent
Asia            5.0  2.898666e+09  5.797333e+08  6.790979e+08
Australia       1.0  2.331602e+07  2.331602e+07           NaN
Europe          6.0  4.579297e+08  7.632161e+07  3.464767e+07
North America   2.0  3.528552e+08  1.764276e+08  1.996696e+08
South America   1.0  2.059153e+08  2.059153e+08           NaN

## 11.

Let's cut % Renewable into 5 bins and group the original dataframe by the Continents, as well as by these new % Renewable bins. Let's check how many countries are in each of these groups.

In [172]:
def issue_eleven():
    import pandas as pd
    Top15 = issue_one() # merged and filtered dataframe
    # Adding a column to cut % Renewable into 5 bins
    Top15['% Renewable bins'] = pd.cut(Top15['% Renewable'], bins = 5)
    # Mapping Countries to Continents
    ContinentDict  = {'China':'Asia', 
                  'United States':'North America', 
                  'Japan':'Asia', 
                  'United Kingdom':'Europe', 
                  'Russian Federation':'Europe', 
                  'Canada':'North America', 
                  'Germany':'Europe', 
                  'India':'Asia',
                  'France':'Europe', 
                  'South Korea':'Asia', 
                  'Italy':'Europe', 
                  'Spain':'Europe', 
                  'Iran':'Asia',
                  'Australia':'Australia', 
                  'Brazil':'South America'}
    # Adding a new column containing the Continents
    Top15['Continent'] = ContinentDict.values()
    # Grouping by Continent and by bin and retrieving the number of countries
    ContinentsBins = Top15.groupby(['Continent','% Renewable bins']).size() # size provides the number of entries for each group
    return ContinentsBins
issue_eleven()

Continent      % Renewable bins
Asia           (2.212, 15.753]     4
               (15.753, 29.227]    1
Australia      (2.212, 15.753]     1
Europe         (2.212, 15.753]     1
               (15.753, 29.227]    3
               (29.227, 42.701]    2
North America  (2.212, 15.753]     1
               (56.174, 69.648]    1
South America  (56.174, 69.648]    1
dtype: int64

## 12.

Finally, let's convert the Population Estimate series to a string with thousands separator using commas.

In [174]:
def answer_twelve():
    import pandas as pd
    Top15 = issue_one() # merged and filtered dataframe
    # Creating a new column with the estimated polulation
    Top15['Population'] = Top15['Energy Supply'] / Top15['Energy Supply per Capita']
    # Converting the Population Estimate series to a string with thousands separator
    PopEst = Top15['Population'].map('{:,}'.format)
    return PopEst
answer_twelve()

Country
China                 1,367,645,161.2903225
United States          317,615,384.61538464
Japan                  127,409,395.97315437
United Kingdom         63,870,967.741935484
Russian Federation            143,500,000.0
Canada                  35,239,864.86486486
Germany                 80,369,696.96969697
India                 1,276,730,769.2307692
France                  63,837,349.39759036
South Korea            49,805,429.864253394
Italy                  59,908,256.880733944
Spain                    46,443,396.2264151
Iran                    77,075,630.25210084
Australia              23,316,017.316017315
Brazil                 205,915,254.23728815
Name: Population, dtype: object

<sub>Juniper notebook server 5.5.0-6f60dc6</sub>
<br></br>
<sub>Python 3.6.5</sub>